name: personalized_skincare_application
description: A personalized skincare app.

publish_to: 'none' # Remove this line if you're planning to publish it

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10

  # Add any additional dependencies here
  # For example:
  # cupertino_icons: ^0.1.3
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/logo.png
    - assets/staff.png
    - assets/alex.png
    - assets/jane.png
    - assets/john.png

