// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx_5Dwn1nPSYG2TFxaL4_kvmsXpiODrZQ',
    appId: '1:913462192780:web:d369455642110ae45f69a9',
    messagingSenderId: '913462192780',
    projectId: 'psa1-9a96b',
    authDomain: 'psa1-9a96b.firebaseapp.com',
    storageBucket: 'psa1-9a96b.firebasestorage.app',
    measurementId: 'G-Q2WKF0XQJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_hZRFrC1migKVl0p2POHphJHH7BtFwks',
    appId: '1:401877048978:android:8f5827af854f462f7ed04b',
    messagingSenderId: '401877048978',
    projectId: 'appt-33942',
    storageBucket: 'appt-33942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuIbRdzcTeips57OyQKRZClzXTuo7ER1M',
    appId: '1:913462192780:ios:fe017c472502983b5f69a9',
    messagingSenderId: '913462192780',
    projectId: 'psa1-9a96b',
    storageBucket: 'psa1-9a96b.firebasestorage.app',
    iosBundleId: 'com.example.personalizedSkincareApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuIbRdzcTeips57OyQKRZClzXTuo7ER1M',
    appId: '1:913462192780:ios:fe017c472502983b5f69a9',
    messagingSenderId: '913462192780',
    projectId: 'psa1-9a96b',
    storageBucket: 'psa1-9a96b.firebasestorage.app',
    iosBundleId: 'com.example.personalizedSkincareApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx_5Dwn1nPSYG2TFxaL4_kvmsXpiODrZQ',
    appId: '1:913462192780:web:f8903bb405effb9b5f69a9',
    messagingSenderId: '913462192780',
    projectId: 'psa1-9a96b',
    authDomain: 'psa1-9a96b.firebaseapp.com',
    storageBucket: 'psa1-9a96b.firebasestorage.app',
    measurementId: 'G-021958LJ3J',
  );
}